/// 注入の間だけペーストボードをパスに差し替え、元の内容に戻す（FR-INJECT-04、DSN-001 §3.1 ステップ 1, 2, 9）。
///
/// 元の内容が機密（`org.nspasteboard.ConcealedType`。パスワードマネージャー等）なら、書き戻さずに空にする。
/// パスワードマネージャーは一定時間後に自分が置いた内容を消すが、書き戻すと changeCount が進んで
/// 「ユーザーが別の内容をコピーした」とみなされ、自動消去が働かなくなるため（オーナー判断）。
/// 機密の内容はデータを読み出さず、プロセス内に複製を持たない。
/// 一時的な内容（`TransientType`）・自動生成の内容（`AutoGeneratedType`）は機密ではないため、従来どおり書き戻す。
@MainActor
public final class PasteboardSwap {
    public enum SwapError: Error, Equatable {
        /// パスを書き込めなかった。元の内容は戻してある（機密の内容は戻さず空のまま）。
        case writeFailed
        /// 退避の途中（機密かの判定から退避を終えるまで）に他のアプリやユーザーが書き換えた。何も書き込んでいない。
        case changedWhileCapturing
    }

    public enum RestoreOutcome: Equatable, Sendable {
        /// 元の内容を書き戻した。
        case restored
        /// 元の内容が機密だったため、書き戻さずに空にした。意図どおりなので失敗ではない。
        case clearedBecauseConcealed
        /// 差し替えた後に他のアプリやユーザーが書き換えていたため、新しい内容を優先して戻さなかった。
        case skippedBecauseReplacedByOthers
        /// 書き戻しに失敗した。
        case failed
        /// 既に復元（または復元の見送り）を済ませていた。
        case alreadyRestored
    }

    /// 注入の後に行うこと。差し替える時点で決める。
    private enum RestorePlan {
        /// 退避した元の内容を書き戻す。
        case writeBack(PasteboardSnapshot)
        /// 元の内容が機密だったため、差し替えたパスを消して空にする。
        case clear
    }

    private let pasteboard: any PasteboardAccessing
    /// 差し替えた直後の changeCount。復元時にこれと異なれば、その後に誰かが書き込んでいる。
    private let changeCountAfterSwap: Int
    /// 復元を済ませたら nil にし、退避した内容（Data）を注入の後まで持ち続けない。
    private var plan: RestorePlan?

    /// 現在の内容を退避してから text を書き込む。元の内容が機密なら退避しない。
    /// - Throws: 書き込めなかった場合 `SwapError.writeFailed`、
    ///   退避の途中で書き換えられた場合 `SwapError.changedWhileCapturing`。
    public init(replacingContentsOf pasteboard: any PasteboardAccessing, with text: String) throws {
        let plan = try Self.makeRestorePlan(for: pasteboard)
        guard pasteboard.replaceContents(with: .transientText(text)) else {
            // 消去だけ済んで書き込めなかった場合に備え、元の内容へ戻してから失敗を返す（機密の内容は戻さない）
            if case .writeBack(let original) = plan {
                _ = pasteboard.replaceContents(with: original)
            }
            throw SwapError.writeFailed
        }
        self.plan = plan
        self.pasteboard = pasteboard
        changeCountAfterSwap = pasteboard.changeCount
    }

    /// 元の内容へ戻す（機密なら空にする）。何度呼んでも書き込むのは 1 回だけ。
    @discardableResult
    public func restore() -> RestoreOutcome {
        guard let plan else { return .alreadyRestored }
        self.plan = nil
        // 注入中にユーザーがコピーした内容を、古い内容で上書きして失わせないため
        guard pasteboard.changeCount == changeCountAfterSwap else { return .skippedBecauseReplacedByOthers }
        switch plan {
        case .writeBack(let original):
            return pasteboard.replaceContents(with: original) ? .restored : .failed
        case .clear:
            // 書き込みの成否に関わらず既存の内容（パス）は消え、元の内容も意図して手放しているため、失敗として扱わない
            _ = pasteboard.replaceContents(with: .empty)
            return .clearedBecauseConcealed
        }
    }

    /// 機密かを判定し、機密でなければ退避する。
    /// 判定と退避はペーストボードを別々に読むため、その間に機密の内容へ書き換わると、機密の内容を退避して
    /// 書き戻してしまい得る。途中で changeCount が変わったら、何も書き込まずにやめる（呼び出し側は副方式へ回す）。
    private static func makeRestorePlan(for pasteboard: any PasteboardAccessing) throws -> RestorePlan {
        let changeCountBeforeCapture = pasteboard.changeCount
        let isConcealed = containsConcealedItem(pasteboard)
        // 判定の直後に書き換わっていれば、新しい内容のデータを読み出さずにやめる
        guard pasteboard.changeCount == changeCountBeforeCapture else { throw SwapError.changedWhileCapturing }
        guard !isConcealed else { return .clear }
        let original = PasteboardSnapshot.capture(from: pasteboard)
        guard pasteboard.changeCount == changeCountBeforeCapture else { throw SwapError.changedWhileCapturing }
        return .writeBack(original)
    }

    /// 型の一覧だけで判定し、機密のデータそのものは読み出さない。
    private static func containsConcealedItem(_ pasteboard: any PasteboardAccessing) -> Bool {
        pasteboard.items.contains { $0.types.contains(PasteboardSnapshot.concealedMarkerType) }
    }
}
